version: 2.1
orbs:
  go: circleci/go@1.10.0
  slack: circleci/slack@4.12.5

jobs:
  run-code: 
    executor:
      name: go/default # Use the default executor from the orb
      tag: '1.21.5' # Specify a version tag
    steps:
      - checkout # checkout source code
      - run: 
          command: go run main.go
      - slack/notify:
          event: fail
          template: basic_fail_1
          mentions: '@channel'
          channel: '#table-droppers'

workflows:
  daily-run-workflow:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - run-code:
          context: slack-testing
